server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.whiskas68.booter.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
